def menuSolicitudes():
    print("- SOLICITUDES -")
    print("--------------------------------------------")
    print("  1. Listado de solicitudes")
    print("--------------------------------------------")
    print("  2. Agregar solicitud")
    print("--------------------------------------------")
    print("  3. Ver estado de las solicitudes")
    print("--------------------------------------------")
    print("  4. Modificar asunto de una solicitud")
    print("--------------------------------------------")
    print("  5. Modificar estado de una solicitud")
    print("--------------------------------------------")
    print("  6. Eliminar solicitud")
    print("--------------------------------------------")
    print("  7. Salir")