def menuSolicitudes():
    print("- SOLICITUDES -")
    print("--------------------------------------------")
    print("  1. Listado de solicitudes")
    print("--------------------------------------------")
    print("  2. Agregar solicitud")
    print("--------------------------------------------")
    print("  3. Ver estado de las solicitudes")
    print("--------------------------------------------")
    print("  4. Modificar estado de solicitud")
    print("--------------------------------------------")
    print("  5. Eliminar solicitud")
    print("--------------------------------------------")

    print("  6. Salir")
    print("--------------------------------------------")