def menuVehiculos():
    print("   * VEHICULOS *")
    print("--------------------------------------------")
    print("     1. Listado de vehiculos")
    print("--------------------------------------------")
    print("     2. Agregar vehiculo")
    print("--------------------------------------------")
    print("     3. Modificar  matricula de vehiculo")
    print("--------------------------------------------")
    print("     4. Eliminar vehiculo")
    print("--------------------------------------------")
    print("     5. Salir")
    print("--------------------------------------------")
